"""mcp

Revision ID: 5e909ac87a6c
Revises: ebc55c241155
Create Date: 2025-08-29 16:15:21.370662

"""

from collections.abc import Sequence

from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "5e909ac87a6c"
down_revision: str | None = "ebc55c241155"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema="public",
        enum_name="toolsource",
        new_values=["INTERNAL", "USER_DEFINED", "MCP"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="tool_call",
                column_name="tool_source",
                existing_server_default="'USER_DEFINED'::toolsource",
            ),
            TableReference(table_schema="public", table_name="tool_definition", column_name="tool_source"),
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema="public",
        enum_name="toolsource",
        new_values=["INTERNAL", "USER_DEFINED"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="tool_call",
                column_name="tool_source",
                existing_server_default="'USER_DEFINED'::toolsource",
            ),
            TableReference(table_schema="public", table_name="tool_definition", column_name="tool_source"),
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
