"""Add Beaker Queue model host

Revision ID: c26ec1a12f09
Revises: 3772048c8bd0
Create Date: 2025-05-09 17:23:33.009272

"""

from collections.abc import Sequence

from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "c26ec1a12f09"
down_revision: str | None = "3772048c8bd0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema="public",
        enum_name="modelhost",
        new_values=["InferD", "Modal", "BeakerQueue"],
        affected_columns=[TableReference(table_schema="public", table_name="model_config", column_name="host")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema="public",
        enum_name="modelhost",
        new_values=["InferD", "Modal"],
        affected_columns=[TableReference(table_schema="public", table_name="model_config", column_name="host")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
