name: Set up uv

runs:
  using: "composite"
  steps:
  - name: Set up Python
    uses: actions/setup-python@v6
    with:
      python-version: "3.11"

  - name: Install uv
    uses: astral-sh/setup-uv@v7
    with:
      version: "0.9.21"
      enable-cache: true

  - name: Install dependencies
    run: uv sync --locked --all-extras --all-packages --dev
    shell: bash