"""add dates to model config

Revision ID: 03da13313751
Revises: 636b1b8f1f03
Create Date: 2025-04-17 15:01:34.431525

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03da13313751"
down_revision: str | None = "636b1b8f1f03"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("model_config", sa.Column("available_time", sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column("model_config", sa.Column("deprecation_time", sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model_config", "deprecation_time")
    op.drop_column("model_config", "available_time")
    # ### end Alembic commands ###
