"""Add Ai2ModelHub host and config

Revision ID: 20c0085a0629
Revises: 4c886e3dd93c
Create Date: 2025-12-15 14:10:19.624749

"""

from collections.abc import Sequence

from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "20c0085a0629"
down_revision: str | None = "4c886e3dd93c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema="public",
        enum_name="modelhost",
        new_values=[
            "InferD",
            "Modal",
            "BeakerQueues",
            "CirrascaleBackend",
            "Cirrascale",
            "ModalOpenAI",
            "TestBackend",
            "Ai2ModelHub",
        ],
        affected_columns=[TableReference(table_schema="public", table_name="model_config", column_name="host")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema="public",
        enum_name="modelhost",
        new_values=["InferD", "Modal", "BeakerQueues", "CirrascaleBackend", "Cirrascale", "ModalOpenAI", "TestBackend"],
        affected_columns=[TableReference(table_schema="public", table_name="model_config", column_name="host")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
