"""Add tool source column

Revision ID: 2c1f383fd067
Revises: 58247c331fed
Create Date: 2025-08-26 10:16:06.341238

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2c1f383fd067"
down_revision: str | None = "58247c331fed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tool_call",
        sa.Column(
            "tool_source",
            postgresql.ENUM("INTERNAL", "USER_DEFINED", name="toolsource", create_type=False),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tool_call", "tool_source")
    # ### end Alembic commands ###
