"""cascade delete rows in the association table

Revision ID: 35175410798d
Revises: 6800257e41d6
Create Date: 2025-09-17 15:04:57.017927

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35175410798d"
down_revision: str | None = "6800257e41d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "message_tool_definition_association_tool_definition_id_fkey",
        "message_tool_definition_association",
        type_="foreignkey",
    )
    op.drop_constraint(
        "message_tool_definition_association_message_id_fkey", "message_tool_definition_association", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("message_tool_definition_association_tool_definition_id_tool_definition_fkey"),
        "message_tool_definition_association",
        "tool_definition",
        ["tool_definition_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("message_tool_definition_association_message_id_message_fkey"),
        "message_tool_definition_association",
        "message",
        ["message_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("message_tool_definition_association_message_id_message_fkey"),
        "message_tool_definition_association",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("message_tool_definition_association_tool_definition_id_tool_definition_fkey"),
        "message_tool_definition_association",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "message_tool_definition_association_message_id_fkey",
        "message_tool_definition_association",
        "message",
        ["message_id"],
        ["id"],
    )
    op.create_foreign_key(
        "message_tool_definition_association_tool_definition_id_fkey",
        "message_tool_definition_association",
        "tool_definition",
        ["tool_definition_id"],
        ["id"],
    )
    # ### end Alembic commands ###
