"""sequence test

Revision ID: 3772048c8bd0
Revises: 724dff1a0068
Create Date: 2025-04-21 16:41:30.731864

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3772048c8bd0"
down_revision: str | None = "724dff1a0068"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        "CREATE SEQUENCE model_config_order_seq INCREMENT BY 10 START WITH 1 OWNED BY model_config.order"
    )
    op.execute("GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "model_config",
        "order",
        server_default=sa.text("nextval('model_config_order_seq')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "model_config",
        "order",
        server_default=None,
    )
    op.execute("GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app")
    op.execute(
        sa.schema.DropSequence(
            sa.Sequence("model_config_order_seq", start=1, increment=10)
        )
    )
    # ### end Alembic commands ###
