"""Add error fields to message table

Revision ID: 440e4ee34a13
Revises: 5da1e4a16ea0
Create Date: 2025-10-24 10:24:50.462116

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "440e4ee34a13"
down_revision: str | None = "5da1e4a16ea0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("error_code", sa.Text(), nullable=True))
    op.add_column("message", sa.Column("error_description", sa.Text(), nullable=True))
    op.add_column("message", sa.Column("error_severity", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "error_severity")
    op.drop_column("message", "error_description")
    op.drop_column("message", "error_code")
    # ### end Alembic commands ###
