"""add mcp source

Revision ID: 5018e6967549
Revises: 5e909ac87a6c
Create Date: 2025-09-02 14:46:59.082327

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5018e6967549"
down_revision: str | None = "5e909ac87a6c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tool_definition", sa.Column("mcp_server_id", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tool_definition", "mcp_server_id")
    # ### end Alembic commands ###
