"""Add tool def table

Revision ID: 58247c331fed
Revises: ac3eb892e1be
Create Date: 2025-08-25 14:00:21.004115

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "58247c331fed"
down_revision: str | None = "ac3eb892e1be"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("INTERNAL", "USER_DEFINED", name="toolsource").create(op.get_bind())
    op.create_table(
        "tool_definition",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tool_name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "tool_source",
            postgresql.ENUM("INTERNAL", "USER_DEFINED", name="toolsource", create_type=False),
            nullable=False,
        ),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("message_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["message.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.execute(sqltext="GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE tool_definition TO app")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #
    op.execute("REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLE tool_definition FROM app")
    op.drop_table("tool_definition")
    sa.Enum("INTERNAL", "USER_DEFINED", name="toolsource").drop(op.get_bind())

    # ### end Alembic commands ###
