"""associate tool defs and prompt templates correctly

Revision ID: 5da1e4a16ea0
Revises: 5a5c5b3e5614
Create Date: 2025-10-09 18:14:21.260874

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5da1e4a16ea0"
down_revision: str | None = "5a5c5b3e5614"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompt_template_tool_definition_association",
        sa.Column("prompt_template_id", sa.Text(), nullable=False),
        sa.Column("tool_definition_id", sa.Text(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["prompt_template_id"], ["prompt_template.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tool_definition_id"], ["tool_definition.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("prompt_template_id", "tool_definition_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("prompt_template_tool_definition_association")
    # ### end Alembic commands ###
