"""add info url to model config

Revision ID: 6800257e41d6
Revises: 277d02390564
Create Date: 2025-09-11 12:48:33.686507

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6800257e41d6"
down_revision: str | None = "277d02390564"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("model_config", sa.Column("information_url", sa.String(), nullable=True))
    op.drop_column("tool_definition", "active")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tool_definition",
        sa.Column("active", sa.BOOLEAN(), server_default=sa.text("true"), autoincrement=False, nullable=False),
    )
    op.drop_column("model_config", "information_url")
    # ### end Alembic commands ###
