"""add infini-gram index column to model configs

Revision ID: 702da94dd19f
Revises: 5018e6967549
Create Date: 2025-09-04 14:09:28.808757

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "702da94dd19f"
down_revision: str | None = "5018e6967549"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "OLMOE_0125_1B_7B",
        "OLMO_2_0325_32B",
        "OLMO_2_1124_13B",
        "PILEVAL_LLAMA",
        "TULU_3_8B",
        "TULU_3_70B",
        "TULU_3_405B",
        name="infini_gram_index_id",
    ).create(op.get_bind())
    op.add_column(
        "model_config",
        sa.Column(
            "infini_gram_index",
            postgresql.ENUM(
                "OLMOE_0125_1B_7B",
                "OLMO_2_0325_32B",
                "OLMO_2_1124_13B",
                "PILEVAL_LLAMA",
                "TULU_3_8B",
                "TULU_3_70B",
                "TULU_3_405B",
                name="infini_gram_index_id",
                create_type=False,
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model_config", "infini_gram_index")
    sa.Enum(
        "OLMOE_0125_1B_7B",
        "OLMO_2_0325_32B",
        "OLMO_2_1124_13B",
        "PILEVAL_LLAMA",
        "TULU_3_8B",
        "TULU_3_70B",
        "TULU_3_405B",
        name="infini_gram_index_id",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
