"""add created and updated times to ModelConfig

Revision ID: 724dff1a0068
Revises: 9089586a14c3
Create Date: 2025-04-21 15:03:48.627023

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "724dff1a0068"
down_revision: str | None = "9089586a14c3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "model_config",
        sa.Column("created_time", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    op.add_column(
        "model_config",
        sa.Column("updated_time", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model_config", "updated_time")
    op.drop_column("model_config", "created_time")
    # ### end Alembic commands ###
