"""Add test model

Revision ID: 97428846ee1e
Revises: 17a551c5bc64
Create Date: 2025-08-05 11:22:54.752659

"""

from collections.abc import Sequence

from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "97428846ee1e"
down_revision: str | None = "17a551c5bc64"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema="public",
        enum_name="modelhost",
        new_values=["InferD", "Modal", "BeakerQueues", "CirrascaleBackend", "Cirrascale", "ModalOpenAI", "TestBackend"],
        affected_columns=[TableReference(table_schema="public", table_name="model_config", column_name="host")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema="public",
        enum_name="modelhost",
        new_values=["InferD", "Modal", "BeakerQueues", "CirrascaleBackend", "Cirrascale", "ModalOpenAI"],
        affected_columns=[TableReference(table_schema="public", table_name="model_config", column_name="host")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
