"""create model configs

Revision ID: 9b467443843c
Revises: 67c7571bc5b8
Create Date: 2025-04-16 10:47:37.604765

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9b467443843c"
down_revision: str | None = "35d1821c4d42"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("text_only", "multi_modal", name="prompttype", schema="model_config").create(op.get_bind())
    op.create_table(
        "model_config",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "prompt_type",
            postgresql.ENUM(
                "text_only",
                "multi_modal",
                name="prompttype",
                schema="model_config",
                inherit_schema=True,
                create_type=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="model_config",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("model_config", schema="model_config")
    sa.Enum("text_only", "multi_modal", name="prompttype", schema="model_config").drop(op.get_bind())
    # ### end Alembic commands ###
