"""rename tool name column

Revision ID: 9ed4a7d05b1b
Revises: e18a18ed104b
Create Date: 2025-08-27 15:17:44.028525

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9ed4a7d05b1b"
down_revision: str | None = "e18a18ed104b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tool_call",
        "tool_source",
        existing_type=postgresql.ENUM("INTERNAL", "USER_DEFINED", name="toolsource"),
    )
    op.add_column("tool_definition", sa.Column("name", sa.String()))
    op.drop_column("tool_definition", "tool_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tool_definition", sa.Column("tool_name", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column("tool_definition", "name")
    op.alter_column(
        "tool_call",
        "tool_source",
        existing_type=postgresql.ENUM("INTERNAL", "USER_DEFINED", name="toolsource"),
        nullable=True,
    )
    # ### end Alembic commands ###
