"""Add can think to model config

Revision ID: a48c549f771e
Revises: 51ded224eed6
Create Date: 2025-08-18 10:39:38.428663

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a48c549f771e"
down_revision: str | None = "51ded224eed6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("model_config", sa.Column("can_think", sa.Boolean(), server_default="false", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model_config", "can_think")
    # ### end Alembic commands ###
