"""add label.message index

Revision ID: a88c3e9a09b0
Revises: 4ecb303b4164
Create Date: 2025-10-30 12:47:02.477305

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a88c3e9a09b0"
down_revision: str | None = "4ecb303b4164"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("label_message_ix"), "label", ["message"], unique=False)
    op.create_index("message_creator_ix", "message", ["creator"], unique=False)
    op.drop_column("message", "agent_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("agent_id", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index("message_creator_ix", table_name="message")
    op.drop_index(op.f("label_message_ix"), table_name="label")
    # ### end Alembic commands ###
