"""add tool def table

Revision ID: ac3eb892e1be
Revises: c0a6e48866a2
Create Date: 2025-08-22 16:36:43.806164

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "ac3eb892e1be"
down_revision: str | None = "c0a6e48866a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
