"""add cirrascale backend model host

Revision ID: b85b60aa5479
Revises: 93d6e3c1967d
Create Date: 2025-07-03 09:15:28.286567

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'b85b60aa5479'
down_revision: str | None = '93d6e3c1967d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema="public",
        enum_name="modelhost",
        new_values=["InferD", "Modal", "BeakerQueue", "CirrascaleBackend"],
        affected_columns=[TableReference(table_schema="public", table_name="model_config", column_name="host")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema="public",
        enum_name="modelhost",
        new_values=["InferD", "Modal", "BeakerQueue"],
        affected_columns=[TableReference(table_schema="public", table_name="model_config", column_name="host")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
