"""create model configs

Revision ID: befde9e1de64
Revises: 67c7571bc5b8
Create Date: 2025-04-16 16:43:24.392840

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "befde9e1de64"
down_revision: str | None = "67c7571bc5b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("text_only", "multi_modal", name="prompttype").create(op.get_bind())
    op.create_table(
        "model_config",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "prompt_type",
            postgresql.ENUM("text_only", "multi_modal", name="prompttype", inherit_schema=True, create_type=False),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("model_config")
    sa.Enum("text_only", "multi_modal", name="prompttype").drop(op.get_bind())
    # ### end Alembic commands ###
