"""create model config table

Revision ID: bf9021f32c31
Revises: 67c7571bc5b8
Create Date: 2025-04-15 13:10:52.887862

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bf9021f32c31"
down_revision: str | None = "67c7571bc5b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA model_config")
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("text_only", "multi_modal", name="prompttype", schema="model_config").create(op.get_bind())
    op.create_table(
        "model_config",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "prompt_type",
            postgresql.ENUM(
                "text_only",
                "multi_modal",
                name="prompttype",
                schema="model_config",
                inherit_schema=True,
                create_type=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="model_config",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("model_config", schema="model_config")
    sa.Enum("text_only", "multi_modal", name="prompttype", schema="model_config").drop(op.get_bind())
    op.execute("DROP SCHEMA model_config")
    # ### end Alembic commands ###
