"""create tool table

Revision ID: c0a6e48866a2
Revises: a48c549f771e
Create Date: 2025-08-19 16:12:09.751534

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c0a6e48866a2"
down_revision: str | None = "a48c549f771e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tool_call",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tool_call_id", sa.Text(), nullable=False),
        sa.Column("tool_name", sa.String(), nullable=False),
        sa.Column("args", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("message_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["message.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(sqltext="GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE tool_call TO app")
    op.drop_column("message", "tool_calls")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message",
        sa.Column(
            "tool_calls", postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), autoincrement=False, nullable=True
        ),
    )
    op.execute("REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLE tool_call FROM app")
    op.drop_table("tool_call")
    # ### end Alembic commands ###
