"""add inference constraints to model config

Revision ID: db6d6c28480d
Revises: 50eb7d8b974b
Create Date: 2025-09-23 13:19:16.515225

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db6d6c28480d"
down_revision: str | None = "50eb7d8b974b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "model_config", sa.Column("temperature_default", sa.Float(), server_default=sa.text("0.7"), nullable=False)
    )
    op.add_column(
        "model_config", sa.Column("temperature_upper", sa.Float(), server_default=sa.text("1.0"), nullable=False)
    )
    op.add_column(
        "model_config", sa.Column("temperature_lower", sa.Float(), server_default=sa.text("0.0"), nullable=False)
    )
    op.add_column(
        "model_config", sa.Column("temperature_step", sa.Float(), server_default=sa.text("0.01"), nullable=False)
    )
    op.add_column("model_config", sa.Column("top_p_default", sa.Float(), server_default=sa.text("1.0"), nullable=False))
    op.add_column("model_config", sa.Column("top_p_upper", sa.Float(), server_default=sa.text("1.0"), nullable=False))
    op.add_column("model_config", sa.Column("top_p_lower", sa.Float(), server_default=sa.text("0.0"), nullable=False))
    op.add_column("model_config", sa.Column("top_p_step", sa.Float(), server_default=sa.text("0.01"), nullable=False))
    op.add_column(
        "model_config", sa.Column("max_tokens_default", sa.Integer(), server_default=sa.text("2048"), nullable=False)
    )
    op.add_column(
        "model_config", sa.Column("max_tokens_upper", sa.Integer(), server_default=sa.text("2048"), nullable=False)
    )
    op.add_column(
        "model_config", sa.Column("max_tokens_lower", sa.Integer(), server_default=sa.text("1"), nullable=False)
    )
    op.add_column(
        "model_config", sa.Column("max_tokens_step", sa.Integer(), server_default=sa.text("1"), nullable=False)
    )
    op.add_column("model_config", sa.Column("stop_default", sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model_config", "stop_default")
    op.drop_column("model_config", "max_tokens_step")
    op.drop_column("model_config", "max_tokens_lower")
    op.drop_column("model_config", "max_tokens_upper")
    op.drop_column("model_config", "max_tokens_default")
    op.drop_column("model_config", "top_p_step")
    op.drop_column("model_config", "top_p_lower")
    op.drop_column("model_config", "top_p_upper")
    op.drop_column("model_config", "top_p_default")
    op.drop_column("model_config", "temperature_step")
    op.drop_column("model_config", "temperature_lower")
    op.drop_column("model_config", "temperature_upper")
    op.drop_column("model_config", "temperature_default")
    # ### end Alembic commands ###
