"""drop message id column

Revision ID: e18a18ed104b
Revises: fb059390a238
Create Date: 2025-08-27 11:27:54.097535

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e18a18ed104b"
down_revision: str | None = "fb059390a238"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tool_call",
        "tool_source",
        existing_type=postgresql.ENUM("INTERNAL", "USER_DEFINED", name="toolsource"),
    )
    op.drop_constraint("tool_definition_message_id_fkey", "tool_definition", type_="foreignkey")
    op.drop_column("tool_definition", "message_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tool_definition", sa.Column("message_id", sa.TEXT(), autoincrement=False))
    op.create_foreign_key("tool_definition_message_id_fkey", "tool_definition", "message", ["message_id"], ["id"])
    op.alter_column(
        "tool_call",
        "tool_source",
        existing_type=postgresql.ENUM("INTERNAL", "USER_DEFINED", name="toolsource"),
    )
    # ### end Alembic commands ###
