"""update infini-gram index ids

Revision ID: e62f9bd0f24b
Revises: a88c3e9a09b0
Create Date: 2025-11-18 17:26:22.529807

"""

from collections.abc import Sequence

from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "e62f9bd0f24b"
down_revision: str | None = "a88c3e9a09b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema="public",
        enum_name="availableinfinigramindexid",
        new_values=[
            "OLMOE_0125_1B_7B",
            "OLMO_2_0325_32B",
            "OLMO_2_1124_13B",
            "OLMO_3_0625_32B_THINK",
            "OLMO_3_0625_32B_INSTRUCT",
            "OLMO_3_0625_7B_INSTRUCT",
            "OLMO_3_0625_7B_THINK",
            "PILEVAL_LLAMA",
            "TULU_3_405B",
            "TULU_3_70B",
            "TULU_3_8B",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="model_config", column_name="infini_gram_index")
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema="public",
        enum_name="availableinfinigramindexid",
        new_values=[
            "OLMOE_0125_1B_7B",
            "OLMO_2_0325_32B",
            "OLMO_2_1124_13B",
            "PILEVAL_LLAMA",
            "TULU_3_8B",
            "TULU_3_70B",
            "TULU_3_405B",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="model_config", column_name="infini_gram_index")
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
