"""fill out model_config

Revision ID: ea686b7953cb
Revises: 4d6e17a0fdf6
Create Date: 2025-04-17 14:37:08.843617

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ea686b7953cb"
down_revision: str | None = "4d6e17a0fdf6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("Base", "Chat", name="modeltype").create(op.get_bind())
    sa.Enum("InferD", "Modal", name="modelhost").create(op.get_bind())
    op.add_column(
        "model_config",
        sa.Column("host", postgresql.ENUM("InferD", "Modal", name="modelhost", create_type=False), nullable=False),
    )
    op.add_column("model_config", sa.Column("name", sa.String(), nullable=False))
    op.add_column("model_config", sa.Column("description", sa.String(), nullable=False))
    op.add_column(
        "model_config",
        sa.Column("model_type", postgresql.ENUM("Base", "Chat", name="modeltype", create_type=False), nullable=False),
    )
    op.add_column("model_config", sa.Column("model_id_on_host", sa.String(), nullable=False))
    op.add_column("model_config", sa.Column("default_system_prompt", sa.String(), nullable=True))
    op.add_column("model_config", sa.Column("family_id", sa.String(), nullable=True))
    op.add_column("model_config", sa.Column("family_name", sa.String(), nullable=True))
    op.add_column("model_config", sa.Column("internal", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model_config", "internal")
    op.drop_column("model_config", "family_name")
    op.drop_column("model_config", "family_id")
    op.drop_column("model_config", "default_system_prompt")
    op.drop_column("model_config", "model_id_on_host")
    op.drop_column("model_config", "model_type")
    op.drop_column("model_config", "description")
    op.drop_column("model_config", "name")
    op.drop_column("model_config", "host")
    sa.Enum("InferD", "Modal", name="modelhost").drop(op.get_bind())
    sa.Enum("Base", "Chat", name="modeltype").drop(op.get_bind())
    # ### end Alembic commands ###
