"""tool call delete

Revision ID: ebc55c241155
Revises: 51773010bab9
Create Date: 2025-08-29 10:41:32.104476

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ebc55c241155"
down_revision: str | None = "51773010bab9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tool_call_message_id_fkey", "tool_call", type_="foreignkey")
    op.create_foreign_key(
        "tool_call_message_id_fkey", "tool_call", "message", ["message_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tool_call_message_id_fkey", "tool_call", type_="foreignkey")
    op.create_foreign_key("tool_call_message_id_fkey", "tool_call", "message", ["message_id"], ["id"])
    # ### end Alembic commands ###
