"""add a tool calling capability field to the db

Revision ID: f34d2db4d75d
Revises: c44d4eee37f6
Create Date: 2025-07-31 17:18:32.638450

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f34d2db4d75d"
down_revision: str | None = "c44d4eee37f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("model_config", sa.Column("can_call_tools", sa.Boolean(), nullable=False, server_default="false"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model_config", "can_call_tools")
    # ### end Alembic commands ###
