"""Add Beaker Queues model host

Revision ID: fae16d8f38d0
Revises: c26ec1a12f09
Create Date: 2025-05-15 13:31:47.408164

"""

from collections.abc import Sequence

from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "fae16d8f38d0"
down_revision: str | None = "c26ec1a12f09"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema="public",
        enum_name="modelhost",
        new_values=["InferD", "Modal", "BeakerQueues"],
        affected_columns=[TableReference(table_schema="public", table_name="model_config", column_name="host")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema="public",
        enum_name="modelhost",
        new_values=["InferD", "Modal", "BeakerQueue"],
        affected_columns=[TableReference(table_schema="public", table_name="model_config", column_name="host")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
