"""add message to tool def table

Revision ID: fb059390a238
Revises: 2c1f383fd067
Create Date: 2025-08-27 11:04:58.211004

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fb059390a238"
down_revision: str | None = "2c1f383fd067"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_tool_definition_association",
        sa.Column("message_id", sa.Text(), nullable=False),
        sa.Column("tool_definition_id", sa.Text(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["message.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tool_definition_id"],
            ["tool_definition.id"],
        ),
        sa.PrimaryKeyConstraint("message_id", "tool_definition_id"),
    )

    op.execute(sqltext="GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE message_tool_definition_association TO app")
    op.alter_column(
        "tool_call",
        "tool_source",
        existing_type=postgresql.ENUM("INTERNAL", "USER_DEFINED", name="toolsource"),
    )

    op.add_column("tool_definition", sa.Column("active", sa.Boolean(), server_default="true", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tool_definition", "active")
    op.alter_column(
        "tool_call",
        "tool_source",
        existing_type=postgresql.ENUM("INTERNAL", "USER_DEFINED", name="toolsource"),
        nullable=True,
    )
    op.drop_table("message_tool_definition_association")
    # ### end Alembic commands ###
