"""create test models table

Revision ID: 6795d068ca86
Revises: 
Create Date: 2025-04-15 10:55:30.968063

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6795d068ca86'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('completion')
    op.drop_table('datachip')
    op.drop_table('label')
    op.drop_index('client_idx', table_name='olmo_user')
    op.drop_table('olmo_user')
    op.drop_index('message_created_ix', table_name='message', postgresql_where='(created <> NULL::timestamp with time zone)')
    op.drop_index('message_original_fkey_ix', table_name='message')
    op.drop_index('message_parent_fkey_ix', table_name='message')
    op.drop_index('message_root_fkey_ix', table_name='message')
    op.drop_table('message')
    op.drop_index('token_type_idx', table_name='client_token')
    op.drop_table('client_token')
    op.drop_table('prompt_template')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_template',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('author', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='prompt_template_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('client_token',
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('client', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("(now() + '1 day'::interval)"), autoincrement=False, nullable=False),
    sa.Column('token_type', postgresql.ENUM('auth', 'invite', name='token_type'), server_default=sa.text("'auth'::token_type"), autoincrement=False, nullable=False),
    sa.Column('creator', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('invite', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invite'], ['client_token.token'], name='client_token_invite_fkey'),
    sa.PrimaryKeyConstraint('token', name='client_token_pkey'),
    sa.UniqueConstraint('invite', name='client_token_invite_key')
    )
    op.create_index('token_type_idx', 'client_token', ['token_type'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('creator', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('opts', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('root', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('parent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('template', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('logprobs', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), autoincrement=False, nullable=True),
    sa.Column('completion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('final', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('original', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('private', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('model_type', postgresql.ENUM('base', 'chat', 'image_prompt', name='model_type'), autoincrement=False, nullable=True),
    sa.Column('finish_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('harmful', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('model_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model_host', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expiration_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('file_urls', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['completion'], ['completion.id'], name='message_completion_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['original'], ['message.id'], name='message_original_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent'], ['message.id'], name='message_parent_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['root'], ['message.id'], name='message_root_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template'], ['prompt_template.id'], name='message_template_fkey'),
    sa.PrimaryKeyConstraint('id', name='message_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('message_root_fkey_ix', 'message', ['root'], unique=False)
    op.create_index('message_parent_fkey_ix', 'message', ['parent'], unique=False)
    op.create_index('message_original_fkey_ix', 'message', ['original'], unique=False)
    op.create_index('message_created_ix', 'message', ['created'], unique=False, postgresql_where='(created <> NULL::timestamp with time zone)')
    op.create_table('olmo_user',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('client', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('terms_accepted_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('acceptance_revoked_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='olmo_user_pkey')
    )
    op.create_index('client_idx', 'olmo_user', ['client'], unique=False)
    op.create_table('label',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('creator', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message'], ['message.id'], name='label_message_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='label_pkey')
    )
    op.create_table('datachip',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('creator', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ref', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='datachip_pkey'),
    sa.UniqueConstraint('ref', name='datachip_ref_key')
    )
    op.create_table('completion',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('input', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('opts', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('model', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sha', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('tokenize_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('queue_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('input_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('output_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='completion_pkey')
    )
    # ### end Alembic commands ###
