#!/usr/bin/env python3
"""Generate Cloud Run Job YAML definitions and Scheduler commands from tier configs.

Usage:
    python generate_jobs.py
    python generate_jobs.py --image gcr.io/my-project/evaluations:latest
    python generate_jobs.py --project my-project --region us-central1
"""

import argparse
import sys
from pathlib import Path

# Add src to path for imports
sys.path.insert(0, str(Path(__file__).parent / "src"))

from evaluations.configs import list_tiers

JOB_YAML_TEMPLATE = """\
apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: eval-{tier_name}
  labels:
    tier: {tier_name}
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      parallelism: {task_count}
      taskCount: {task_count}
      template:
        spec:
          containers:
            - image: {image}
              resources:
                limits:
                  cpu: "{cpu}"
                  memory: {memory}
              env:
                - name: EVAL_TIER
                  value: {tier_name}
                # Secrets from Secret Manager
                - name: LITELLM_PROXY_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: litellm-proxy-api-key
                      key: latest
                - name: PGHOST
                  valueFrom:
                    secretKeyRef:
                      name: pg-host
                      key: latest
                - name: PGPORT
                  valueFrom:
                    secretKeyRef:
                      name: pg-port
                      key: latest
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: pg-user
                      key: latest
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: pg-password
                      key: latest
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws-access-key-id
                      key: latest
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-secret-access-key
                      key: latest
          timeoutSeconds: {timeout_seconds}
          serviceAccountName: {service_account}
"""

# Resource allocation per tier
TIER_RESOURCES = {
    "smoke": {"cpu": "2", "memory": "4Gi"},
    "standard": {"cpu": "2", "memory": "4Gi"},
    "deployment": {"cpu": "4", "memory": "8Gi"},
}


def generate_job_yaml(
    tier,
    image: str = "IMAGE_URL",
    service_account: str = "SERVICE_ACCOUNT",
) -> str:
    """Generate Cloud Run Job YAML for a tier."""
    tier_name = tier.name.value
    resources = TIER_RESOURCES.get(tier_name, {"cpu": "2", "memory": "4Gi"})

    return JOB_YAML_TEMPLATE.format(
        tier_name=tier_name,
        task_count=tier.task_count,
        image=image,
        cpu=resources["cpu"],
        memory=resources["memory"],
        timeout_seconds=tier.timeout_minutes * 60,
        service_account=service_account,
    )


def generate_deploy_script(
    tiers,
    project: str,
    region: str,
    service_account: str,
) -> str:
    """Generate shell script to deploy jobs and create schedulers."""
    lines = [
        "#!/bin/bash",
        "# Deploy Cloud Run Jobs and create Cloud Scheduler triggers",
        "# Generated by generate_jobs.py",
        "",
        "set -e",
        "",
        f'PROJECT="{project}"',
        f'REGION="{region}"',
        f'SERVICE_ACCOUNT="{service_account}"',
        "",
        "# Deploy Cloud Run Jobs",
    ]

    for tier in tiers:
        tier_name = tier.name.value
        lines.append(f'echo "Deploying eval-{tier_name}..."')
        lines.append(
            f"gcloud run jobs replace cloud-run-jobs/{tier_name}.yaml "
            f'--region "$REGION" --project "$PROJECT"'
        )
        lines.append("")

    lines.append("# Create Cloud Scheduler jobs")

    for tier in tiers:
        tier_name = tier.name.value
        job_name = f"eval-{tier_name}"
        scheduler_name = f"{job_name}-schedule"

        if not tier.schedule:
            lines.append(f"# {scheduler_name}: No schedule (manual trigger only)")
            lines.append("")
            continue

        lines.append(f'echo "Creating scheduler {scheduler_name}..."')

        # Delete existing scheduler if it exists (ignore errors)
        lines.append(
            f"gcloud scheduler jobs delete {scheduler_name} "
            f'--location "$REGION" --project "$PROJECT" --quiet 2>/dev/null || true'
        )

        # Create new scheduler
        uri = (
            f"https://$REGION-run.googleapis.com/apis/run.googleapis.com/v1/"
            f"namespaces/$PROJECT/jobs/{job_name}:run"
        )
        lines.append(
            f"gcloud scheduler jobs create http {scheduler_name} \\\n"
            f'  --location "$REGION" \\\n'
            f'  --project "$PROJECT" \\\n'
            f'  --schedule "{tier.schedule}" \\\n'
            f'  --time-zone "UTC" \\\n'
            f'  --uri "{uri}" \\\n'
            f"  --http-method POST \\\n"
            f'  --oauth-service-account-email "$SERVICE_ACCOUNT"'
        )
        lines.append("")

    lines.append('echo "Done!"')
    lines.append("")
    lines.append("# Manual execution commands:")
    for tier in tiers:
        tier_name = tier.name.value
        lines.append(f'# gcloud run jobs execute eval-{tier_name} --region "$REGION" --project "$PROJECT"')

    return "\n".join(lines)


def generate_teardown_script(
    tiers,
    project: str,
    region: str,
) -> str:
    """Generate shell script to delete jobs and schedulers."""
    lines = [
        "#!/bin/bash",
        "# Delete Cloud Run Jobs and Cloud Scheduler triggers",
        "# Generated by generate_jobs.py",
        "",
        "set -e",
        "",
        f'PROJECT="{project}"',
        f'REGION="{region}"',
        "",
        "# Delete Cloud Scheduler jobs",
    ]

    for tier in tiers:
        tier_name = tier.name.value
        scheduler_name = f"eval-{tier_name}-schedule"
        lines.append(
            f"gcloud scheduler jobs delete {scheduler_name} "
            f'--location "$REGION" --project "$PROJECT" --quiet 2>/dev/null || true'
        )

    lines.append("")
    lines.append("# Delete Cloud Run Jobs")

    for tier in tiers:
        tier_name = tier.name.value
        job_name = f"eval-{tier_name}"
        lines.append(
            f"gcloud run jobs delete {job_name} "
            f'--region "$REGION" --project "$PROJECT" --quiet 2>/dev/null || true'
        )

    lines.append("")
    lines.append('echo "Done!"')

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate Cloud Run Job YAMLs and deploy scripts")
    parser.add_argument("--image", default="IMAGE_URL", help="Container image URL")
    parser.add_argument("--service-account", default="SERVICE_ACCOUNT", help="Service account email")
    parser.add_argument("--project", default="PROJECT_ID", help="GCP project ID")
    parser.add_argument("--region", default="us-central1", help="GCP region")
    parser.add_argument("--output-dir", default="cloud-run-jobs", help="Output directory")
    args = parser.parse_args()

    output_dir = Path(__file__).parent / args.output_dir
    output_dir.mkdir(exist_ok=True)

    tiers = list_tiers()

    # Generate Job YAMLs
    print("Generating Cloud Run Job YAMLs...")
    for tier in tiers:
        yaml_content = generate_job_yaml(
            tier,
            image=args.image,
            service_account=args.service_account,
        )
        output_file = output_dir / f"{tier.name.value}.yaml"
        output_file.write_text(yaml_content)
        print(f"  {output_file}")
        print(f"    Task count: {tier.task_count}")
        print(f"    Timeout: {tier.timeout_minutes} min")
        print(f"    Schedule: {tier.schedule or '(manual)'}")

    # Generate deploy script
    print("\nGenerating deploy script...")
    deploy_script = generate_deploy_script(
        tiers,
        project=args.project,
        region=args.region,
        service_account=args.service_account,
    )
    deploy_file = output_dir / "deploy.sh"
    deploy_file.write_text(deploy_script)
    deploy_file.chmod(0o755)
    print(f"  {deploy_file}")

    # Generate teardown script
    print("\nGenerating teardown script...")
    teardown_script = generate_teardown_script(
        tiers,
        project=args.project,
        region=args.region,
    )
    teardown_file = output_dir / "teardown.sh"
    teardown_file.write_text(teardown_script)
    teardown_file.chmod(0o755)
    print(f"  {teardown_file}")

    print("\nDone! Next steps:")
    print(f"  1. Update placeholders in {output_dir}/*.yaml")
    print(f"  2. Run: {deploy_file}")


if __name__ == "__main__":
    main()
