#!/bin/bash
# Deploy Cloud Run Jobs and create Cloud Scheduler triggers
# Generated by generate_jobs.py

set -e

PROJECT="my-project"
REGION="us-central1"
SERVICE_ACCOUNT="evaluations@my-project.iam.gserviceaccount.com"

# Deploy Cloud Run Jobs
echo "Deploying eval-smoke..."
gcloud run jobs replace cloud-run-jobs/smoke.yaml --region "$REGION" --project "$PROJECT"

echo "Deploying eval-standard..."
gcloud run jobs replace cloud-run-jobs/standard.yaml --region "$REGION" --project "$PROJECT"

echo "Deploying eval-deployment..."
gcloud run jobs replace cloud-run-jobs/deployment.yaml --region "$REGION" --project "$PROJECT"

# Create Cloud Scheduler jobs
echo "Creating scheduler eval-smoke-schedule..."
gcloud scheduler jobs delete eval-smoke-schedule --location "$REGION" --project "$PROJECT" --quiet 2>/dev/null || true
gcloud scheduler jobs create http eval-smoke-schedule \
  --location "$REGION" \
  --project "$PROJECT" \
  --schedule "0 */6 * * *" \
  --time-zone "UTC" \
  --uri "https://$REGION-run.googleapis.com/apis/run.googleapis.com/v1/namespaces/$PROJECT/jobs/eval-smoke:run" \
  --http-method POST \
  --oauth-service-account-email "$SERVICE_ACCOUNT"

echo "Creating scheduler eval-standard-schedule..."
gcloud scheduler jobs delete eval-standard-schedule --location "$REGION" --project "$PROJECT" --quiet 2>/dev/null || true
gcloud scheduler jobs create http eval-standard-schedule \
  --location "$REGION" \
  --project "$PROJECT" \
  --schedule "0 2 * * 1,4" \
  --time-zone "UTC" \
  --uri "https://$REGION-run.googleapis.com/apis/run.googleapis.com/v1/namespaces/$PROJECT/jobs/eval-standard:run" \
  --http-method POST \
  --oauth-service-account-email "$SERVICE_ACCOUNT"

# eval-deployment-schedule: No schedule (manual trigger only)

echo "Done!"

# Manual execution commands:
# gcloud run jobs execute eval-smoke --region "$REGION" --project "$PROJECT"
# gcloud run jobs execute eval-standard --region "$REGION" --project "$PROJECT"
# gcloud run jobs execute eval-deployment --region "$REGION" --project "$PROJECT"