"""add agent_id to message

Revision ID: 2d0eb25156b5
Revises: 440e4ee34a13
Create Date: 2025-10-27 16:32:43.945463

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d0eb25156b5"
down_revision: str | None = "440e4ee34a13"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("agent_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "agent_id")
    # ### end Alembic commands ###
