"""Add index to message.creator

Revision ID: 4ecb303b4164
Revises: 5da1e4a16ea0
Create Date: 2025-10-29 13:39:04.930919

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4ecb303b4164"
down_revision: str | None = "5da1e4a16ea0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("message_creator_ix", "message", ["creator"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("message_creator_ix", table_name="message")
    # ### end Alembic commands ###
