"""tool definition table

Revision ID: 51773010bab9
Revises: c0a6e48866a2
Create Date: 2025-08-27 17:39:33.163153

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "51773010bab9"
down_revision: str | None = "c0a6e48866a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("INTERNAL", "USER_DEFINED", name="toolsource").create(op.get_bind())
    op.create_table(
        "tool_definition",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "tool_source",
            postgresql.ENUM("INTERNAL", "USER_DEFINED", name="toolsource", create_type=False),
            nullable=False,
        ),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE tool_definition TO app")
    op.create_table(
        "message_tool_definition_association",
        sa.Column("message_id", sa.Text(), nullable=False),
        sa.Column("tool_definition_id", sa.Text(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["message.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tool_definition_id"],
            ["tool_definition.id"],
        ),
        sa.PrimaryKeyConstraint("message_id", "tool_definition_id"),
    )
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE message_tool_definition_association TO app")
    op.add_column(
        "tool_call",
        sa.Column(
            "tool_source",
            postgresql.ENUM("INTERNAL", "USER_DEFINED", name="toolsource", create_type=False),
            nullable=False,
            server_default="USER_DEFINED",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tool_call", "tool_source")
    op.drop_table("message_tool_definition_association")
    op.drop_table("tool_definition")
    sa.Enum("INTERNAL", "USER_DEFINED", name="toolsource").drop(op.get_bind())
    # ### end Alembic commands ###
