"""make tool calls jsonb

Revision ID: 51ded224eed6
Revises: ba2462b3122c
Create Date: 2025-08-11 14:30:03.353922

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "51ded224eed6"
down_revision: str | None = "ba2462b3122c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "message",
        "tool_calls",
        existing_type=postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())),
        type_=sa.ARRAY(postgresql.JSONB(astext_type=sa.Text())),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "message",
        "tool_calls",
        existing_type=sa.ARRAY(postgresql.JSONB(astext_type=sa.Text())),
        type_=postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
