"""add more data to prompt templates

Revision ID: 5a5c5b3e5614
Revises: 13971fd04e39
Create Date: 2025-10-08 17:21:54.121501

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5a5c5b3e5614"
down_revision: str | None = "13971fd04e39"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prompt_template", sa.Column("creator", sa.String(), nullable=False))
    op.add_column("prompt_template", sa.Column("opts", postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column(
        "prompt_template",
        sa.Column("model_type", postgresql.ENUM("Base", "Chat", name="modeltype", create_type=False), nullable=False),
    )
    op.add_column("prompt_template", sa.Column("file_urls", sa.ARRAY(sa.Text()), nullable=True))
    op.add_column(
        "prompt_template", sa.Column("extra_parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.drop_column("prompt_template", "author")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prompt_template", sa.Column("author", sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column("prompt_template", "extra_parameters")
    op.drop_column("prompt_template", "file_urls")
    op.drop_column("prompt_template", "model_type")
    op.drop_column("prompt_template", "opts")
    op.drop_column("prompt_template", "creator")
    # ### end Alembic commands ###
