"""add multimodal model config

Revision ID: 636b1b8f1f03
Revises: ea686b7953cb
Create Date: 2025-04-17 14:48:59.236055

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "636b1b8f1f03"
down_revision: str | None = "ea686b7953cb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("FirstMessage", "AllMessages", "NoRequirement", name="filerequiredtopromptoption").create(op.get_bind())
    op.create_table(
        "multi_modal_model_config",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("accepted_file_types", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("max_files_per_message", sa.Integer(), nullable=True),
        sa.Column(
            "require_file_to_prompt",
            postgresql.ENUM(
                "FirstMessage", "AllMessages", "NoRequirement", name="filerequiredtopromptoption", create_type=False
            ),
            nullable=True,
        ),
        sa.Column("max_total_file_size", sa.Integer(), nullable=True),
        sa.Column("allow_files_in_followups", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["model_config.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("multi_modal_model_config")
    sa.Enum("FirstMessage", "AllMessages", "NoRequirement", name="filerequiredtopromptoption").drop(op.get_bind())
    # ### end Alembic commands ###
