"""add files-only model type

Revision ID: 93d6e3c1967d
Revises: fae16d8f38d0
Create Date: 2025-06-12 15:51:42.563187

"""

from collections.abc import Sequence

from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "93d6e3c1967d"
down_revision: str | None = "fae16d8f38d0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema="public",
        enum_name="prompttype",
        new_values=["TEXT_ONLY", "MULTI_MODAL", "FILES_ONLY"],
        affected_columns=[TableReference(table_schema="public", table_name="model_config", column_name="prompt_type")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema="public",
        enum_name="prompttype",
        new_values=["TEXT_ONLY", "MULTI_MODAL"],
        affected_columns=[TableReference(table_schema="public", table_name="model_config", column_name="prompt_type")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
