"""add thinking and tool calls to messages

Revision ID: ba2462b3122c
Revises: 97428846ee1e
Create Date: 2025-08-11 12:02:37.325037

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba2462b3122c"
down_revision: str | None = "97428846ee1e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("thinking", sa.String(), nullable=True))
    op.add_column("message", sa.Column("tool_calls", sa.ARRAY(sa.JSON()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "tool_calls")
    op.drop_column("message", "thinking")
    # ### end Alembic commands ###
