"""add order property to model config

Revision ID: c97651b81c1a
Revises: 03da13313751
Create Date: 2025-04-17 15:40:14.281660

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c97651b81c1a"
down_revision: str | None = "03da13313751"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("model_config", sa.Column("order", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model_config", "order")
    # ### end Alembic commands ###
