"""add extra_parameter column

Revision ID: dc5ccc64fa6f
Revises: 50eb7d8b974b
Create Date: 2025-09-25 11:03:33.426363

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dc5ccc64fa6f"
down_revision: str | None = "50eb7d8b974b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("extra_parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "extra_parameters")
    # ### end Alembic commands ###
