"""add input_parts column

Revision ID: edaadce92f0a
Revises: e62f9bd0f24b
Create Date: 2025-11-25 15:31:52.303553

"""

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

from db.models.input_parts import InputPart
from db.models.pydantic_type import PydanticType

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "edaadce92f0a"
down_revision: str | None = "e62f9bd0f24b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message",
        sa.Column("input_parts", sa.ARRAY(PydanticType(InputPart)), nullable=True),  # type:ignore[arg-type] # pyright: ignore[reportArgumentType]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "input_parts")
    # ### end Alembic commands ###
