name: e2e API Tests
on:
  push:
    branches: [main]
  pull_request:

jobs:
  e2e-test:
    environment: test
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ vars.DATABASE_URL }}
      AUTH_DOMAIN: ${{ vars.AUTH_DOMAIN }}
      AUTH_AUDIENCE: ${{ vars.AUTH_AUDIENCE }}
      HUBSPOT_TOKEN: ${{ secrets.HUBSPOT_TOKEN }}
      ASTA_MCP_API_KEY: ${{ secrets.ASTA_MCP_API_KEY }}
      BEAKER_USER_TOKEN: ${{ secrets.BEAKER_USER_TOKEN }}
      CIRRASCALE_API_KEY: ${{ secrets.CIRRASCALE_API_KEY }}
      MODAL_OPENAI_API_KEY: ${{ secrets.MODAL_OPENAI_API_KEY }}
      E2E_AUTH0_CLIENT_ID: ${{ secrets.E2E_AUTH0_CLIENT_ID }}
      AI2_MODEL_HUB_API_KEY: ${{ secrets.AI2_MODEL_HUB_API_KEY }}
      ENV: test
    steps:
      - uses: actions/checkout@v6

      - name: Setup Config
        env:
          CONFIG_JSON: ${{ secrets.CONFIG_JSON }}
        run: |
          echo $CONFIG_JSON | base64 --decode > config.json

      - name: Setup Gcloud Credentials
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
        run: |
          echo $GOOGLE_SERVICE_ACCOUNT | base64 --decode > service_account.json
 
      - name: Set up uv
        uses: ./.github/actions/set-up-uv

      - name: Test fastapi with pytest
        env:
          E2E_AUTH0_CLIENT_ID: ${{ secrets.E2E_AUTH0_CLIENT_ID }}
          E2E_AUTH0_CLIENT_SECRET: ${{ secrets.E2E_AUTH0_CLIENT_SECRET }}
        run: uv run pytest ./apps/api/e2e
