name: Verify

concurrency:
  group: unit-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:

jobs:
    unit-test:
      runs-on: ubuntu-latest
      env:
        AUTH_DOMAIN: ${{ vars.AUTH_DOMAIN }}
        AUTH_AUDIENCE: ${{ vars.AUTH_AUDIENCE }}
        ENV: test
      steps:
        - uses: actions/checkout@v6

        - name: Set up repo
          uses: ./.github/actions/set-up-repo

        - name: Test with pytest
          run: just test

    type-check:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v6

        - name: Set up repo
          uses: ./.github/actions/set-up-repo

        - run: just type-check

    lint:
      runs-on: ubuntu-latest  
      steps:
      - uses: actions/checkout@v6
  
      - name: Set up repo
        uses: ./.github/actions/set-up-repo

      - run: just lint --output-format=github
      
    format:
      runs-on: ubuntu-latest 
      steps:
        - uses: actions/checkout@v6
    
        - name: Set up repo
          uses: ./.github/actions/set-up-repo

        - run: just format --check